# Basic data types

In [ ]:
#Integers 
x = 3
#print the type of x
print(type(x))
# Addition : add 1 to x and print the result
print(x + 1)
# Subtraction; subtract 1 from x and print the result
print(x - 1)
# Multiplication; multiply x with 2 and print the result
print(x * 2)
# Exponentiation; print the square of x
print(x ** 2)

<class 'int'>
4
2
6
9


In [ ]:
#floats
y = 2.5
#print the type of y
print(type(y))
#use operator *= to double the value of y and print y 
y *= 2
print(y)
#use operator += to add 3 to y and print y 
y += 3
print(y)

<class 'float'>
5.0
8.0


In [ ]:
#Strings 
s = "hello"
# Capitalize the above string and print it
print(s.capitalize())
#Convert the string to uppercase and print it
print(s.upper())
# Right-justify the string, padding with 2 spaces print it;
print(s.rjust(len(s) + 2, " "))
# Center the string, padding with 2 spaces print it;
print(s.center(len(s) + 4, " "))
# Replace all instances of letter l  with "(ell)" and print it;
print(s.replace("l", "(ell)"))
str = " world "
# Strip leading and trailing whitespace in the above string and print
print(str.strip(" "))

Hello
HELLO
  hello
  hello  
he(ell)(ell)o
world


# Containers

In [ ]:
#Lists
#create a list of first five natural numbers
list1 = [1,2,3,4]
#change the 3rd element to "foo" and print list1
list1[2] = "foo"
print(list1)
list2 = ["bar"]
#append list2 to list1 and print the result
list1.append(list2)
print(list1)
#add list2 to list1 using extend and print the result
list1.extend(list2)
print(list1)
#remove last element in list1 using pop and print list1
list1.pop()
print(list1)


[1, 2, 'foo', 4]
[1, 2, 'foo', 4, ['bar']]
[1, 2, 'foo', 4, ['bar'], 'bar']
[1, 2, 'foo', 4, ['bar']]


In [ ]:
#Slicing 
nums = list(range(5))
#print a slice from index 2 to 4 (exclusive)
print(nums[2:4])
#print a slice from index 2 to 4 (exclusive)
print(nums[2:4])
# Slice indices can be negative; 
print(nums[:-3]) 
# Assign the [8,9] new list to a slice from index 2 to 4 (exclusive)
new_list = [8, 9]
nums[2:4] = new_list
print(nums)

[2, 3]
[2, 3]
[0, 1]
[0, 1, 8, 9, 4]


In [ ]:
#Loops
nums = [0, 1, 2, 3, 4]
squares = []
# append squares of each element in nums to squares using for loop
for num in nums:
  squares.append(nums[num]**2)
print(squares)
####

animals = ['cat', 'dog', 'monkey']
#print index and elements in the list using enumerate and for loop
for index, element in enumerate(animals):
  print(index, element)

#print squares of even numbers using list comprehensions
nums = [0, 1, 2, 3, 4]
even_squares = [num**2 for num in range(5) if num % 2 == 0]
print(even_squares)

[0, 1, 4, 9, 16]
0 cat
1 dog
2 monkey
[0, 4, 16]


In [ ]:
#Dictionaries
#create a dictionary with keys = (cat, dog) and items = (cute,furry)
d = {"cat":"cute", "dog":"furry"}
print(d)
#set an entry {fish:wet}
d["fish"] = "wet"
print(d)
#remove the entry with key= cat 
del d["cat"]
print(d)
# Get an element with a default;
print(d.get('monkey', 'N/A'))
# get an element with key= fish and print it
print(d.get("fish"))
#print all keys in dictionary
print(d.keys())
#print all items in dictionary
print(d.items())

{'cat': 'cute', 'dog': 'furry'}
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}
{'dog': 'furry', 'fish': 'wet'}
N/A
wet
dict_keys(['dog', 'fish'])
dict_items([('dog', 'furry'), ('fish', 'wet')])


In [ ]:
#sets 
#create a set with elements cat, dog and fish
s = ["fish", "cat", "dog"]
print(s)
#add monkey to the set
s.append("monkey")
print(s)
#remove fish from the set 
s.remove("fish")
print(s)
#checks if an element is in the set
print('fish' in animals)

['fish', 'cat', 'dog']
['fish', 'cat', 'dog', 'monkey']
['cat', 'dog', 'monkey']
False


# Numpy

In [ ]:
#importing the numpy package 
import numpy as np
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
#print the shape of the array
print(b.shape)
#print an array of all zeros of shape(2,2)
c = np.zeros([2,2])
print(c)
#print an array of all ones of shape(1,2)
d = np.ones([1,2])
print(d)
#print an array of shape (3,3) with all elements in array = 7
e = np.array([[7,7,7],[7,7,7],[7,7,7]])
print(e)
#print an array filled with random values of shape (2,2)
f = np.random.rand(2,2)
print(f)

(2, 3)
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.97481025 0.25003468]
 [0.87885399 0.98162248]]


In [ ]:
#ARRAY INDEXING

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use slicing to print out the subarray consisting of the first 2 rows and columns 1 and 2;
print(a[0:2, 1:3])
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
# print one element from each row of a using the indices in b
for item in np.choose(b, a.T):
  print(item)
# add 10 to one element from each row of a using the indices in b
a[np.arange(4),b] += 10
print(a)

[[2 3]
 [6 7]]
1
6
7
11
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
#Boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])
#Print a numpy array of Booleans where elements of a are bigger than 2 ,shape=(3,2)
y = [[True if i[j] > 2 else False for j in range(len(a)-1)] for i in a]
y = np.array(y)
print(y)
#a rank 1 array consisting of the elements of a that are bigger than 2
print(y.flatten())
x = np.array([1, 2]) 
#print data type of the array
print(x.dtype)
#create an array [[1,2],[3,4]] with data type int64.
b = np.array([[1,2],[3,4]], dtype=np.int64)
print(b)

[[False False]
 [ True  True]
 [ True  True]]
[False False  True  True  True  True]
int64
[[1 2]
 [3 4]]


In [ ]:
#Array math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
#print elementwise addition using numpy function
print(np.add(y, x))
#print elementwise difference using numpy function
print(np.subtract(y, x))
#print elementwise multiplication using numpy function
print(np.multiply(y, x))
#print elementwise division using numpy function
print(np.divide(y, x))
#print elementwise square root using numpy function
print(np.sqrt(y, x))

[[ 6.  8.]
 [10. 12.]]
[[4. 4.]
 [4. 4.]]
[[ 5. 12.]
 [21. 32.]]
[[5.         3.        ]
 [2.33333333 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

#print Inner product of vectors
print(np.inner(x, y))
#print matrix / vector product of x and v 
print(np.dot(x, v)) 
#print matrix / vector product of x and y 
print(np.dot(x, y)) 

[[17 23]
 [39 53]]
[29 67]
[[19 22]
 [43 50]]


In [ ]:
x = np.array([[1,2],[3,4]])
#print sum of all elements in array
print(x.sum())
#print sum of elements in each row
print([x[i].sum() for i in range(len(x))])
#print sum of elements in each column
y = np.array([[x[i][j] for i in range(2)] for j in range(2)])
print([y[i].sum() for i in range(len(y))])

10
[3, 7]
[4, 6]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
#Create an empty matrix with the same shape as x and print 
y = np.empty(x.shape)
print(y)
# create an array y by adding  the vector v to each row of the matrix x with an explicit loop 
#print y
y = np.array([x[i] + v for i in range(4)])
print(y)
#Add v to each row of x using broadcasting
#store the result in matrix y and print y
y = x + v
print(y)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]
 [4.9e-323 5.4e-323 5.9e-323]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
v = np.array([1,2,3])  
w = np.array([4,5])
#reshape v to(3,1) using numpy function and print it
print(np.reshape(v, (3,1)))

[[1]
 [2]
 [3]]
